//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetResourcesExtensions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetResourcesExtensions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ResourceReader class does not know how to read this version of .resources files. Expected version: {0}  This file: {1}.
        /// </summary>
        internal static string Arg_ResourceFileUnsupportedVersion {
            get {
                return ResourceManager.GetString("Arg_ResourceFileUnsupportedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream was not readable.
        /// </summary>
        internal static string Argument_StreamNotReadable {
            get {
                return ResourceManager.GetString("Argument_StreamNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream was not writable..
        /// </summary>
        internal static string Argument_StreamNotWritable {
            get {
                return ResourceManager.GetString("Argument_StreamNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream length must be non-negative and less than 2^31 - 1 - origin..
        /// </summary>
        internal static string ArgumentOutOfRange_StreamLength {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_StreamLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file.  The specified type doesn&apos;t exist..
        /// </summary>
        internal static string BadImageFormat_InvalidType {
            get {
                return ResourceManager.GetString("BadImageFormat_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file. String length must be non-negative..
        /// </summary>
        internal static string BadImageFormat_NegativeStringLength {
            get {
                return ResourceManager.GetString("BadImageFormat_NegativeStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file.  The specified data length &apos;{0}&apos; is not a valid position in the stream..
        /// </summary>
        internal static string BadImageFormat_ResourceDataLengthInvalid {
            get {
                return ResourceManager.GetString("BadImageFormat_ResourceDataLengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file. A resource name extends past the end of the stream..
        /// </summary>
        internal static string BadImageFormat_ResourceNameCorrupted {
            get {
                return ResourceManager.GetString("BadImageFormat_ResourceNameCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file. The resource name for name index {0} extends past the end of the stream..
        /// </summary>
        internal static string BadImageFormat_ResourceNameCorrupted_NameIndex {
            get {
                return ResourceManager.GetString("BadImageFormat_ResourceNameCorrupted_NameIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file. Invalid offset &apos;{0}&apos; into data section..
        /// </summary>
        internal static string BadImageFormat_ResourcesDataInvalidOffset {
            get {
                return ResourceManager.GetString("BadImageFormat_ResourcesDataInvalidOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file. Unable to read resources from this file because of invalid header information. Try regenerating the .resources file..
        /// </summary>
        internal static string BadImageFormat_ResourcesHeaderCorrupted {
            get {
                return ResourceManager.GetString("BadImageFormat_ResourcesHeaderCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file. String for name index &apos;{0}&apos; extends past the end of the file..
        /// </summary>
        internal static string BadImageFormat_ResourcesIndexTooLong {
            get {
                return ResourceManager.GetString("BadImageFormat_ResourcesIndexTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file. Invalid offset &apos;{0}&apos; into name section..
        /// </summary>
        internal static string BadImageFormat_ResourcesNameInvalidOffset {
            get {
                return ResourceManager.GetString("BadImageFormat_ResourcesNameInvalidOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file. Resource name extends past the end of the file..
        /// </summary>
        internal static string BadImageFormat_ResourcesNameTooLong {
            get {
                return ResourceManager.GetString("BadImageFormat_ResourcesNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type serialized in the .resources file was not the same type that the .resources file said it contained. Expected &apos;{0}&apos; but read &apos;{1}&apos;..
        /// </summary>
        internal static string BadImageFormat_ResType_SerBlobMismatch {
            get {
                return ResourceManager.GetString("BadImageFormat_ResType_SerBlobMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt .resources file.  The specified type doesn&apos;t match the available data in the stream..
        /// </summary>
        internal static string BadImageFormat_TypeMismatch {
            get {
                return ResourceManager.GetString("BadImageFormat_TypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupted Resource Format detected..
        /// </summary>
        internal static string DNTRESEXT_BINFMT_CORRUPTED {
            get {
                return ResourceManager.GetString("DNTRESEXT_BINFMT_CORRUPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid header format version: {0} . This reader can only read up to version {1} ..
        /// </summary>
        internal static string DNTRESEXT_BINFMT_FMT_VER_INVALID {
            get {
                return ResourceManager.GetString("DNTRESEXT_BINFMT_FMT_VER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format version is invalid: {0} . The reader can only read up to {1}..
        /// </summary>
        internal static string DNTRESEXT_BINFMT_HDR_VER_INVALID {
            get {
                return ResourceManager.GetString("DNTRESEXT_BINFMT_HDR_VER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read {0} bytes while expecting to read {1} bytes..
        /// </summary>
        internal static string DNTRESEXT_BINFMT_INVALID_DATA_LENGTH {
            get {
                return ResourceManager.GetString("DNTRESEXT_BINFMT_INVALID_DATA_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read the resource header. It&apos;s magic value is invalid..
        /// </summary>
        internal static string DNTRESEXT_BINFMT_INVALID_MAGIC {
            get {
                return ResourceManager.GetString("DNTRESEXT_BINFMT_INVALID_MAGIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format specifies that the resource types allowed are all up to {0} but read a value of {1} that is higher than the mask..
        /// </summary>
        internal static string DNTRESEXT_BINFMT_INVALID_TYPEID {
            get {
                return ResourceManager.GetString("DNTRESEXT_BINFMT_INVALID_TYPEID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid header. The specified data position alignment is possibly corrupted. This header stream is untrusted..
        /// </summary>
        internal static string DNTRESEXT_BINFMT_INVALIDALIGNMENT {
            get {
                return ResourceManager.GetString("DNTRESEXT_BINFMT_INVALIDALIGNMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid header. Header must exactly contain the CURRENTFORMATS phrase..
        /// </summary>
        internal static string DNTRESEXT_BINFMT_NO_CURRENTFORMATS_HEADER {
            get {
                return ResourceManager.GetString("DNTRESEXT_BINFMT_NO_CURRENTFORMATS_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid header. Header must exactly contain the DATAPOSALIGNMENT phrase..
        /// </summary>
        internal static string DNTRESEXT_BINFMT_NO_DATAPOSALIGNMENT_HEADER {
            get {
                return ResourceManager.GetString("DNTRESEXT_BINFMT_NO_DATAPOSALIGNMENT_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid header. Header must exactly contain the DATAPOSITIONS phrase..
        /// </summary>
        internal static string DNTRESEXT_BINFMT_NO_DATAPOSITIONS_HEADER {
            get {
                return ResourceManager.GetString("DNTRESEXT_BINFMT_NO_DATAPOSITIONS_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid header. Header must exactly contain the DATAPOSITIONSCOUNT phrase..
        /// </summary>
        internal static string DNTRESEXT_BINFMT_NO_DATAPOSITIONSCOUNT_HEADER {
            get {
                return ResourceManager.GetString("DNTRESEXT_BINFMT_NO_DATAPOSITIONSCOUNT_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid header. Header must exactly contain the DOTNETTYPE phrase..
        /// </summary>
        internal static string DNTRESEXT_BINFMT_NO_DOTNETTYPE_HEADER {
            get {
                return ResourceManager.GetString("DNTRESEXT_BINFMT_NO_DOTNETTYPE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to detect header end. This suggests that the data are corrupted..
        /// </summary>
        internal static string DNTRESEXT_BINFMT_NO_HEADER_END {
            get {
                return ResourceManager.GetString("DNTRESEXT_BINFMT_NO_HEADER_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid header. Header must exactly contain the HEADERVERSION phrase..
        /// </summary>
        internal static string DNTRESEXT_BINFMT_NO_HEADERVERSION_HEADER {
            get {
                return ResourceManager.GetString("DNTRESEXT_BINFMT_NO_HEADERVERSION_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid header start. Header must begin with RESOURCE..
        /// </summary>
        internal static string DNTRESEXT_BINFMT_NO_RESOURCE_HEADER {
            get {
                return ResourceManager.GetString("DNTRESEXT_BINFMT_NO_RESOURCE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid header. Header must exactly contain the RESOURCENAME phrase..
        /// </summary>
        internal static string DNTRESEXT_BINFMT_NO_RESOURCENAME_HEADER {
            get {
                return ResourceManager.GetString("DNTRESEXT_BINFMT_NO_RESOURCENAME_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid header. Header must exactly contain the RESOURCESIZE phrase..
        /// </summary>
        internal static string DNTRESEXT_BINFMT_NO_RESOURCESIZE_HEADER {
            get {
                return ResourceManager.GetString("DNTRESEXT_BINFMT_NO_RESOURCESIZE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid header. Header must exactly contain the RESOURCETYPE phrase..
        /// </summary>
        internal static string DNTRESEXT_BINFMT_NO_RESOURCETYPE_HEADER {
            get {
                return ResourceManager.GetString("DNTRESEXT_BINFMT_NO_RESOURCETYPE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid header. Header must exactly contain the SUPPORTEDHEADERVERSION phrase..
        /// </summary>
        internal static string DNTRESEXT_BINFMT_NO_SUPPORTEDHEADERVERSION_HEADER {
            get {
                return ResourceManager.GetString("DNTRESEXT_BINFMT_NO_SUPPORTEDHEADERVERSION_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid header. Header must exactly contain the VALUE phrase..
        /// </summary>
        internal static string DNTRESEXT_BINFMT_NO_VALUE_HEADER {
            get {
                return ResourceManager.GetString("DNTRESEXT_BINFMT_NO_VALUE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid header. Header must exactly contain the VERSION phrase..
        /// </summary>
        internal static string DNTRESEXT_BINFMT_NO_VERSION_HEADER {
            get {
                return ResourceManager.GetString("DNTRESEXT_BINFMT_NO_VERSION_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupted resource header format detected..
        /// </summary>
        internal static string DNTRESEXT_BINFMT_RESHEADER_CORRUPTED {
            get {
                return ResourceManager.GetString("DNTRESEXT_BINFMT_RESHEADER_CORRUPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid header. Header version is {0} , which cannot be read by this reader..
        /// </summary>
        internal static string DNTRESEXT_BINFMT_VER_MISMATCH {
            get {
                return ResourceManager.GetString("DNTRESEXT_BINFMT_VER_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FileReferenceEncoding enumeration does not support or honor the usage of &apos;{0}&apos; as a file encoding..
        /// </summary>
        internal static string DNTRESEXT_FILEREFENC_INVALIDENC {
            get {
                return ResourceManager.GetString("DNTRESEXT_FILEREFENC_INVALIDENC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to encoding must be a named constant of FileReferenceEncoding enumeration..
        /// </summary>
        internal static string DNTRESEXT_FILEREFENC_OOR {
            get {
                return ResourceManager.GetString("DNTRESEXT_FILEREFENC_OOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided file with name {0} cannot be found by the system. Check whether the given path is correct and retry..
        /// </summary>
        internal static string DNTRESEXT_FILEREFEXT_OPENFILE_FILENOTFOUND {
            get {
                return ResourceManager.GetString("DNTRESEXT_FILEREFEXT_OPENFILE_FILENOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serialization to string failed. See/Consult the inner exception for more details..
        /// </summary>
        internal static string DNTRESEXT_FILEREFEXT_SERSTRING_FAILED {
            get {
                return ResourceManager.GetString("DNTRESEXT_FILEREFEXT_SERSTRING_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected the chunk to be closed but instead it is malformed..
        /// </summary>
        internal static string DNTRESEXT_HRFMT_CHUNK_INVALID {
            get {
                return ResourceManager.GetString("DNTRESEXT_HRFMT_CHUNK_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupted byte array was read. Expected to read at least {0} chunks but instead only the {1} chunks were successfully retrieved..
        /// </summary>
        internal static string DNTRESEXT_HRFMT_DATA_CORRUPTED {
            get {
                return ResourceManager.GetString("DNTRESEXT_HRFMT_DATA_CORRUPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The human-readable format reader does not currently support downloading data from the Internet..
        /// </summary>
        internal static string DNTRESEXT_HRFMT_FILEREF_DOWNLOAD_UNSUPPORTED {
            get {
                return ResourceManager.GetString("DNTRESEXT_HRFMT_FILEREF_DOWNLOAD_UNSUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not the custom human-readable format. Error occured..
        /// </summary>
        internal static string DNTRESEXT_HRFMT_GENERIC_ERROR {
            get {
                return ResourceManager.GetString("DNTRESEXT_HRFMT_GENERIC_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected to read {0} bytes but read {1} bytes..
        /// </summary>
        internal static string DNTRESEXT_HRFMT_INVALID_DATA_LEN {
            get {
                return ResourceManager.GetString("DNTRESEXT_HRFMT_INVALID_DATA_LEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected the value to be ended , but the resource value does still continue. Have you forgotten to close the resource?.
        /// </summary>
        internal static string DNTRESEXT_HRFMT_INVALID_RESOURCEVAL_LAYOUT {
            get {
                return ResourceManager.GetString("DNTRESEXT_HRFMT_INVALID_RESOURCEVAL_LAYOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version read is higher than the version that this reader can read..
        /// </summary>
        internal static string DNTRESEXT_HRFMT_VER_MISMATCH {
            get {
                return ResourceManager.GetString("DNTRESEXT_HRFMT_VER_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse the numeric value defined in &apos;version&apos; header. Internal error occured..
        /// </summary>
        internal static string DNTRESEXT_HRFMT_VERHDR_UNPARSEABLE {
            get {
                return ResourceManager.GetString("DNTRESEXT_HRFMT_VERHDR_UNPARSEABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This header cannot be read with this version of the class. Please use a reader that supports header version {0} or higher..
        /// </summary>
        internal static string DNTRESEXT_JSONFMT_CANNOT_READ_HEADER {
            get {
                return ResourceManager.GetString("DNTRESEXT_JSONFMT_CANNOT_READ_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serialization failed for type &apos;{0}&apos;. See the internal parser error message for more information..
        /// </summary>
        internal static string DNTRESEXT_JSONFMT_COULDNOTSER {
            get {
                return ResourceManager.GetString("DNTRESEXT_JSONFMT_COULDNOTSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A decoder version was not found. Internal error detected..
        /// </summary>
        internal static string DNTRESEXT_JSONFMT_DECODE_VERSION_NOT_FOUND {
            get {
                return ResourceManager.GetString("DNTRESEXT_JSONFMT_DECODE_VERSION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bytes read were not equal to the expected bytes (Expected {0} while read {1} bytes)..
        /// </summary>
        internal static string DNTRESEXT_JSONFMT_INVALID_DATA_LENMISMATCH {
            get {
                return ResourceManager.GetString("DNTRESEXT_JSONFMT_INVALID_DATA_LENMISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each bytearray chunk must be exactly {0} characters..
        /// </summary>
        internal static string DNTRESEXT_JSONFMT_INVALID_DATA_TOPIC_ALIGNMENT {
            get {
                return ResourceManager.GetString("DNTRESEXT_JSONFMT_INVALID_DATA_TOPIC_ALIGNMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource type element must be either a number or a string that describes the resource type..
        /// </summary>
        internal static string DNTRESEXT_JSONFMT_INVALID_RESTYPEDATATYPE {
            get {
                return ResourceManager.GetString("DNTRESEXT_JSONFMT_INVALID_RESTYPEDATATYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic value was incorrect - this reader cannot read this resources format..
        /// </summary>
        internal static string DNTRESEXT_JSONFMT_INVALIDMAGIC {
            get {
                return ResourceManager.GetString("DNTRESEXT_JSONFMT_INVALIDMAGIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file or stream might not be the mdcdi1315 Resource JSON format , and cannot be read..
        /// </summary>
        internal static string DNTRESEXT_JSONFMT_MSG_GENERIC {
            get {
                return ResourceManager.GetString("DNTRESEXT_JSONFMT_MSG_GENERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type read in ResourceType field was invalid..
        /// </summary>
        internal static string DNTRESEXT_JSONFMT_RESTYPE_INVALID {
            get {
                return ResourceManager.GetString("DNTRESEXT_JSONFMT_RESTYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read a newer version of the JSON resources file. Version found was {0} . Either this reader does not currently have such information or the stream is corrupted..
        /// </summary>
        internal static string DNTRESEXT_JSONFMT_VERMISMATCH {
            get {
                return ResourceManager.GetString("DNTRESEXT_JSONFMT_VERMISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write additional resources after Close() is called..
        /// </summary>
        internal static string DNTRESEXT_JSONFMT_WRITER_CLOSED {
            get {
                return ResourceManager.GetString("DNTRESEXT_JSONFMT_WRITER_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse the resource because impartial data were retrieved..
        /// </summary>
        internal static string DNTRESEXT_MSINIFMT_CANNOT_PARSE {
            get {
                return ResourceManager.GetString("DNTRESEXT_MSINIFMT_CANNOT_PARSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find entity end. The entity might have been misconstructed..
        /// </summary>
        internal static string DNTRESEXT_MSINIFMT_ENT_INVALID {
            get {
                return ResourceManager.GetString("DNTRESEXT_MSINIFMT_ENT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read header data. This might not be the MS-INI DotNetResourcesExtensions format..
        /// </summary>
        internal static string DNTRESEXT_MSINIFMT_INVALID_DATA {
            get {
                return ResourceManager.GetString("DNTRESEXT_MSINIFMT_INVALID_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or unknown sequence detected: &apos;-{0}&apos;.
        /// </summary>
        internal static string DNTRESEXT_MSINIFMT_INVALID_ENCODE_SEQUENCE {
            get {
                return ResourceManager.GetString("DNTRESEXT_MSINIFMT_INVALID_ENCODE_SEQUENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This reader cannot read this format version ({0})..
        /// </summary>
        internal static string DNTRESEXT_MSINIFMT_VER_MISMATCH {
            get {
                return ResourceManager.GetString("DNTRESEXT_MSINIFMT_VER_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use an unreadable stream for reading it&apos;s data..
        /// </summary>
        internal static string DNTRESEXT_STRCannotBeUsed_Read {
            get {
                return ResourceManager.GetString("DNTRESEXT_STRCannotBeUsed_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use an unwriteable stream for writing data..
        /// </summary>
        internal static string DNTRESEXT_STRCannotBeUsed_Write {
            get {
                return ResourceManager.GetString("DNTRESEXT_STRCannotBeUsed_Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The underlying stream must be a readable stream..
        /// </summary>
        internal static string DNTRESEXT_StreamUnreadable {
            get {
                return ResourceManager.GetString("DNTRESEXT_StreamUnreadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The underlying stream must be a writeable stream..
        /// </summary>
        internal static string DNTRESEXT_StreamUnwriteable {
            get {
                return ResourceManager.GetString("DNTRESEXT_StreamUnwriteable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse the type defined in the &apos;type&apos; attribute. Value was invalid..
        /// </summary>
        internal static string DNTRESEXT_XMLFMT_CANNOT_PARSE_TYPE {
            get {
                return ResourceManager.GetString("DNTRESEXT_XMLFMT_CANNOT_PARSE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A resource object deserialization error occured..
        /// </summary>
        internal static string DNTRESEXT_XMLFMT_DESER_FAILED {
            get {
                return ResourceManager.GetString("DNTRESEXT_XMLFMT_DESER_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The byte array contents could not be read because not all expected chunks were read..
        /// </summary>
        internal static string DNTRESEXT_XMLFMT_INVALID_CHUNK_NUMBER {
            get {
                return ResourceManager.GetString("DNTRESEXT_XMLFMT_INVALID_CHUNK_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The magic value of the header is either unsupported or indicates data corruption..
        /// </summary>
        internal static string DNTRESEXT_XMLFMT_INVALID_MAGIC {
            get {
                return ResourceManager.GetString("DNTRESEXT_XMLFMT_INVALID_MAGIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupted byte array detected. Expected to read {0} bytes while read {1} bytes..
        /// </summary>
        internal static string DNTRESEXT_XMLFMT_INVALID_RESULT_LENGTH {
            get {
                return ResourceManager.GetString("DNTRESEXT_XMLFMT_INVALID_RESULT_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML Resources header was not found..
        /// </summary>
        internal static string DNTRESEXT_XMLFMT_NO_CXML_HEADER_FOUND {
            get {
                return ResourceManager.GetString("DNTRESEXT_XMLFMT_NO_CXML_HEADER_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This resource object type is not supported in version 1: {0}.
        /// </summary>
        internal static string DNTRESEXT_XMLFMT_TYPENOTSUPPORTED_V1 {
            get {
                return ResourceManager.GetString("DNTRESEXT_XMLFMT_TYPENOTSUPPORTED_V1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This resource object type is not supported in version 2: {0}.
        /// </summary>
        internal static string DNTRESEXT_XMLFMT_TYPENOTSUPPORTED_V2 {
            get {
                return ResourceManager.GetString("DNTRESEXT_XMLFMT_TYPENOTSUPPORTED_V2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to load a version not supported by this class. These data require a reader that support version {0} or later..
        /// </summary>
        internal static string DNTRESEXT_XMLFMT_VER_MISMATCH {
            get {
                return ResourceManager.GetString("DNTRESEXT_XMLFMT_VER_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///Resource Name: {1}.
        /// </summary>
        internal static string DotNetResourcesException_Message {
            get {
                return ResourceManager.GetString("DotNetResourcesException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many bytes in what should have been a 7 bit encoded Int32..
        /// </summary>
        internal static string Format_Bad7BitInt32 {
            get {
                return ResourceManager.GetString("Format_Bad7BitInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration already finished..
        /// </summary>
        internal static string InvalidOperation_EnumEnded {
            get {
                return ResourceManager.GetString("InvalidOperation_EnumEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration has not started. Call MoveNext..
        /// </summary>
        internal static string InvalidOperation_EnumNotStarted {
            get {
                return ResourceManager.GetString("InvalidOperation_EnumNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource was of type &apos;{0}&apos; instead of String - call GetObject instead..
        /// </summary>
        internal static string InvalidOperation_ResourceNotString_Type {
            get {
                return ResourceManager.GetString("InvalidOperation_ResourceNotString_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource writer has already been closed and cannot be edited..
        /// </summary>
        internal static string InvalidOperation_ResourceWriterSaved {
            get {
                return ResourceManager.GetString("InvalidOperation_ResourceWriterSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property can be changed only before the enumeration..
        /// </summary>
        internal static string InvalidResXBasePathOperation {
            get {
                return ResourceManager.GetString("InvalidResXBasePathOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResX file {0} cannot be parsed..
        /// </summary>
        internal static string InvalidResXFile {
            get {
                return ResourceManager.GetString("InvalidResXFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResX input is not valid. Cannot find valid &quot;resheader&quot; tags for the ResX reader and writer type names..
        /// </summary>
        internal static string InvalidResXFileReaderWriterTypes {
            get {
                return ResourceManager.GetString("InvalidResXFileReaderWriterTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a type for a name.  The type name was &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidResXNoType {
            get {
                return ResourceManager.GetString("InvalidResXNoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a name for the resource with the value &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidResXResourceNoName {
            get {
                return ResourceManager.GetString("InvalidResXResourceNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} in the data at line {1}, position {2}, cannot be loaded because it threw the following exception during construction: {3}.
        /// </summary>
        internal static string InvocationException {
            get {
                return ResourceManager.GetString("InvocationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item named &apos;{0}&apos; of type &apos;{1}&apos; cannot be added to the resource file because it is not serializable..
        /// </summary>
        internal static string NotSerializableType {
            get {
                return ResourceManager.GetString("NotSerializableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} on line {1}, position {2} threw the following exception while being converted: {3}.
        /// </summary>
        internal static string NotSupported {
            get {
                return ResourceManager.GetString("NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This platform does not support binary serialized resources..
        /// </summary>
        internal static string NotSupported_BinarySerializedResources {
            get {
                return ResourceManager.GetString("NotSupported_BinarySerializedResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read resources that depend on serialization..
        /// </summary>
        internal static string NotSupported_ResourceObjectSerialization {
            get {
                return ResourceManager.GetString("NotSupported_ResourceObjectSerialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not support seeking..
        /// </summary>
        internal static string NotSupported_UnseekableStream {
            get {
                return ResourceManager.GetString("NotSupported_UnseekableStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This .resources file should not be read with this reader. The resource reader type is &quot;{0}&quot;..
        /// </summary>
        internal static string NotSupported_WrongResourceReader_Type {
            get {
                return ResourceManager.GetString("NotSupported_WrongResourceReader_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access a closed resource set..
        /// </summary>
        internal static string ObjectDisposed_ResourceSet {
            get {
                return ResourceManager.GetString("ObjectDisposed_ResourceSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use of ResourceManager for custom types is disabled. Set the MSBuild Property CustomResourceTypesSupport to true in order to enable it..
        /// </summary>
        internal static string ResourceManager_ReflectionNotAllowed {
            get {
                return ResourceManager.GetString("ResourceManager_ReflectionNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource &apos;{0}&apos; was not found..
        /// </summary>
        internal static string ResourceNotFoundException_Ctor {
            get {
                return ResourceManager.GetString("ResourceNotFoundException_Ctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///This exception is related with the category &apos;{1}&apos;. 
        ///Original Parser Error: {2}.
        /// </summary>
        internal static string ResourceParsersException_Message {
            get {
                return ResourceManager.GetString("ResourceParsersException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResourceReader is closed..
        /// </summary>
        internal static string ResourceReaderIsClosed {
            get {
                return ResourceManager.GetString("ResourceReaderIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream is not a valid resource file..
        /// </summary>
        internal static string Resources_StreamNotValid {
            get {
                return ResourceManager.GetString("Resources_StreamNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource &apos;{0}&apos; is not a &apos;{1}&apos; - it is a &apos;{2}&apos;..
        /// </summary>
        internal static string ResourceTypeMismatchException_Ctor {
            get {
                return ResourceManager.GetString("ResourceTypeMismatchException_Ctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///Expected Resource Type: {1}
        ///Recieved Resource Type: {2}
        ///Resource Name: {3}.
        /// </summary>
        internal static string ResourceTypeMismatchException_Message {
            get {
                return ResourceManager.GetString("ResourceTypeMismatchException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource writer has been saved.  You may not edit it..
        /// </summary>
        internal static string ResXResourceWriterSaved {
            get {
                return ResourceManager.GetString("ResXResourceWriterSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} could not be read from the data in line {1}, position {2}.  The type&apos;s internal structure may have changed.  Either implement ISerializable on the type or provide a type converter that can provide a more reliable conversion format, such as text or an array of bytes.  The conversion exception was: {3}.
        /// </summary>
        internal static string SerializationException {
            get {
                return ResourceManager.GetString("SerializationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} in the data at line {1}, position {2} cannot be located..
        /// </summary>
        internal static string TypeLoadException {
            get {
                return ResourceManager.GetString("TypeLoadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load a converter for type {0}..
        /// </summary>
        internal static string TypeLoadException_CannotLoadConverter {
            get {
                return ResourceManager.GetString("TypeLoadException_CannotLoadConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} cannot be located..
        /// </summary>
        internal static string TypeLoadExceptionShort {
            get {
                return ResourceManager.GetString("TypeLoadExceptionShort", resourceCulture);
            }
        }
    }
}
